### ISSUE TITLE
"학교 2개 이상 존재함"

### ISSUE THREAD

**Issue by RTFTR** [hegelty/pycomcigan#3]
안녕하십니까

최근에 시간표 알리미 앱을 디스코드로 통해서 개발하고 있는데
학교 이름이 다른 이름이 존재한다고 해서 충돌하고 있습니다..

```
@bot.command()
async def 시간표알림(ctx):
    get_school_code("경기")

    try:
        timetable = TimeTable(week_num=0, school_name="성지고등학교")
    except Exception as e:
        embed = discord.Embed(title="❌오류", description=(f'시간표를 불러오는 데 실패했습니다: {e}'))
        await ctx.send(embed=embed)

    print(timetable.timetable[2][12][timetable.MONDAY])
    print(timetable.homeroom(2, 12))
  ```
  
컴시간알리미에서도 성지고등학교가 2개 있는데 문제는 하나는 이름이 "부산성지고등학교"라서 출력이 잘 되네요
혹시 최근에 폐교된 다른 성지고등학교 이름이 아직 잔여 데이터로 남아있는 것 때문에 발생하는건가요..? get_school_code("경기")로 따로 해봐도 잘 안되네요

빠른 답변 해주시면 고맙겠습니다. 감사합니다.

**Comment by hegelty** [comment]
아래와 같은 코드를 실행하면

```py
from pycomcigan import get_school_code

print(get_school_code("성지고"))
```

```
[[24966, '경기', '성지고등학교', 40203], [24966, '부산', '부산성지고등학교', 93342]]
```

위와 같은 출력을 볼 수 있습니다.
배열에서 해당하는 학교를 찾아

```py
from pycomcigan import TimeTable

print(TimeTable(school_name="성지고", school_code=40203))
```
위와 같이 불러오시면 됩니다.

**Comment by RTFTR** [comment]
> 아래와 같은 코드를 실행하면
> 
> ```py
> from pycomcigan import get_school_code
> 
> print(get_school_code("성지고"))
> ```
> 
> ```
> [[24966, '경기', '성지고등학교', 40203], [24966, '부산', '부산성지고등학교', 93342]]
> ```
> 
> 위와 같은 출력을 볼 수 있습니다.
> 배열에서 해당하는 학교를 찾아
> 
> ```py
> from pycomcigan import TimeTable
> 
> print(TimeTable(school_name="성지고", school_code=40203))
> ```
> 위와 같이 불러오시면 됩니다.

감사합니다!
